### ISSUE TITLE
ndjson - read overflow

### ISSUE THREAD

**Issue by pauldreik** [simdjson/simdjson#1310]
Use the fuzzer in https://github.com/simdjson/simdjson/pull/1304

To reproduce, checkout that branch and then:
```shell
fuzz/build_fuzzer_variants.sh
mkdir -p out/ndjson
build-sanitizers-O0/fuzz/fuzz_ndjson out/ndjson
```
It should crash easily, within seconds.

Threads=Off

Crashing input, base64: AwA5ICIg
```
==17328==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6140002b97dc at pc 0x7fa3dc4c425e bp 0x7ffdcff1dcb0 sp 0x7ffdcff1dca8
READ of size 32 at 0x6140002b97dc thread T0
    #0 0x7fa3dc4c425d in simdjson::haswell::(anonymous namespace)::simd::base8_numeric<unsigned char>::load(unsigned char const*) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../include/simdjson/haswell/simd.h:78:14
    #1 0x7fa3dc4c425d in simdjson::haswell::(anonymous namespace)::simd::simd8<unsigned char>::simd8(unsigned char const*) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../include/simdjson/haswell/simd.h:231
    #2 0x7fa3dc4c425d in simdjson::haswell::(anonymous namespace)::backslash_and_quote::copy_and_find(unsigned char const*, unsigned char*) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../include/simdjson/haswell/stringparsing.h:33
    #3 0x7fa3dc4c425d in simdjson::haswell::(anonymous namespace)::stringparsing::parse_string(unsigned char const*, unsigned char*) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../include/simdjson/generic/stringparsing.h:83
    #4 0x7fa3dc4c425d in simdjson::haswell::(anonymous namespace)::stage2::tape_builder::visit_string(simdjson::haswell::(anonymous namespace)::stage2::json_iterator&, unsigned char const*, bool) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../src/generic/stage2/tape_builder.h:148
    #5 0x7fa3dc4c425d in simdjson::haswell::(anonymous namespace)::stage2::tape_builder::visit_root_string(simdjson::haswell::(anonymous namespace)::stage2::json_iterator&, unsigned char const*) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../src/generic/stage2/tape_builder.h:158
    #6 0x7fa3dc4c425d in simdjson::error_code simdjson::haswell::(anonymous namespace)::stage2::json_iterator::visit_root_primitive<simdjson::haswell::(anonymous namespace)::stage2::tape_builder>(simdjson::haswell::(anonymous namespace)::stage2::tape_builder&, unsigned char const*) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../src/generic/stage2/json_iterator.h:284
    #7 0x7fa3dc4c425d in simdjson::haswell::(anonymous namespace)::stage2::tape_builder::visit_root_primitive(simdjson::haswell::(anonymous namespace)::stage2::json_iterator&, unsigned char const*) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../src/generic/stage2/tape_builder.h:97
    #8 0x7fa3dc4c425d in simdjson::error_code simdjson::haswell::(anonymous namespace)::stage2::json_iterator::walk_document<true, simdjson::haswell::(anonymous namespace)::stage2::tape_builder>(simdjson::haswell::(anonymous namespace)::stage2::tape_builder&) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../src/generic/stage2/json_iterator.h:140
    #9 0x7fa3dc4c425d in simdjson::error_code simdjson::haswell::(anonymous namespace)::stage2::tape_builder::parse_document<true>(simdjson::haswell::dom_parser_implementation&, simdjson::dom::document&) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../src/generic/stage2/tape_builder.h:93
    #10 0x7fa3dc4c425d in simdjson::haswell::dom_parser_implementation::stage2_next(simdjson::dom::document&) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../src/haswell/dom_parser_implementation.cpp:152
    #11 0x537635 in simdjson::dom::document_stream::next() /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../include/simdjson/dom/document_stream-inl.h:175:35
    #12 0x52fdcd in simdjson::dom::document_stream::iterator::operator++() /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../include/simdjson/dom/document_stream-inl.h:125:10

```

**Comment by lemire** [comment]
It seems that the following returns an error condition... 

``` C++    
     simdjson::dom::parser parser;
     simdjson::padded_string input = decode_base64("AwA5ICIg");
     print_hex(input);
     simdjson::dom::document_stream stream;
     auto error = parser.parse_many(input).get(stream);
 ```


According to the stack trace, the error should occur within `simdjson::dom::document_stream::iterator::operator++()` but it should never get called. The call to `parser.parse_many` should fail.

Decoding the base64 input AwA5ICIg I get

03 00 39 20 22 20

which is invalid JSON.

(Verified with https://cryptii.com/pipes/base64-to-hex) 

Running the code above (without a loop evidently) with sanitizers does not appear to reveal an issue...

```
$ git checkout  dlemire/document_stream_fuzz_issues
$ cmake -DSIMDJSON_SANITIZE=ON -Bstream_issues
$  cmake --build stream_issues --target document_stream_tests
$ ./stream_issues/tests/document_stream_tests
```


Reference:
https://github.com/simdjson/simdjson/pull/1318/files

**Comment by lemire** [comment]
Accidentally, one could set the batch size to an unreasonable value (e.g., 0): let us guard against it: https://github.com/simdjson/simdjson/pull/1319

**Comment by pauldreik** [comment]
I have updated [my branch](https://github.com/simdjson/simdjson/pull/1304) so that this particular unit test triggers (when address sanitizer is used).

At some point, we should consider merging the ndjson fuzzer instead and let oss-fuzz handle all the minimization and separating the distinct failures for us.

For now, I hope the modified unit test will make it easier to track down the error.

```
paul@ink:~/code/delaktig/simdjson$ build-sanitizers-O0/tests/document_stream_tests 
Running tests against this implementation: haswell(Intel/AMD AVX2)
------------------------------------------------------------
Running document_stream tests.
Running issue1307
hex  : 0C 00 20 
ascii:  __ __ __
Running issue1308
hex  : 6D C7 6D 5B 41 00 
ascii: m__ __m__[__A__ __
Running issue1309
hex  : 09 00 39 38 0A 39 0A 0A 0A 0A 22 22 5F 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 26 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 5F 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 26 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 DB DB DB DB DB DB DB DB DB 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 26 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 26 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 00 
ascii:  __ __9__8__ __9__ __ __ __ __"__"_____"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__&__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"_____"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__&__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__&__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__&__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__ __
Running issue1310
hex  : 20 20 5B 20 33 2C 31 5D 20 22 22 22 22 22 22 22 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 
ascii:  __ __[__ __3__,__1__]__ __"__"__"__"__"__"__"__ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __
=================================================================
==9949==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60700000006f at pc 0x7f91e904a25e bp 0x7ffee5e6c850 sp 0x7ffee5e6c848
READ of size 32 at 0x60700000006f thread T0
    #0 0x7f91e904a25d in simdjson::haswell::(anonymous namespace)::simd::base8_numeric<unsigned char>::load(unsigned char const*) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../include/simdjson/haswell/simd.h:78:14
    #1 0x7f91e904a25d in simdjson::haswell::(anonymous namespace)::simd::simd8<unsigned char>::simd8(unsigned char const*) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../include/simdjson/haswell/simd.h:231
    #2 0x7f91e904a25d in simdjson::haswell::(anonymous namespace)::backslash_and_quote::copy_and_find(unsigned char const*, unsigned char*) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../include/simdjson/haswell/stringparsing.h:33
    #3 0x7f91e904a25d in simdjson::haswell::(anonymous namespace)::stringparsing::parse_string(unsigned char const*, unsigned char*) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../include/simdjson/generic/stringparsing.h:83
    #4 0x7f91e904a25d in simdjson::haswell::(anonymous namespace)::stage2::tape_builder::visit_string(simdjson::haswell::(anonymous namespace)::stage2::json_iterator&, unsigned char const*, bool) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../src/generic/stage2/tape_builder.h:148
    #5 0x7f91e904a25d in simdjson::haswell::(anonymous namespace)::stage2::tape_builder::visit_root_string(simdjson::haswell::(anonymous namespace)::stage2::json_iterator&, unsigned char const*) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../src/generic/stage2/tape_builder.h:158
    #6 0x7f91e904a25d in simdjson::error_code simdjson::haswell::(anonymous namespace)::stage2::json_iterator::visit_root_primitive<simdjson::haswell::(anonymous namespace)::stage2::tape_builder>(simdjson::haswell::(anonymous namespace)::stage2::tape_builder&, unsigned char const*) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../src/generic/stage2/json_iterator.h:284
    #7 0x7f91e904a25d in simdjson::haswell::(anonymous namespace)::stage2::tape_builder::visit_root_primitive(simdjson::haswell::(anonymous namespace)::stage2::json_iterator&, unsigned char const*) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../src/generic/stage2/tape_builder.h:97
    #8 0x7f91e904a25d in simdjson::error_code simdjson::haswell::(anonymous namespace)::stage2::json_iterator::walk_document<true, simdjson::haswell::(anonymous namespace)::stage2::tape_builder>(simdjson::haswell::(anonymous namespace)::stage2::tape_builder&) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../src/generic/stage2/json_iterator.h:140
    #9 0x7f91e904a25d in simdjson::error_code simdjson::haswell::(anonymous namespace)::stage2::tape_builder::parse_document<true>(simdjson::haswell::dom_parser_implementation&, simdjson::dom::document&) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../src/generic/stage2/tape_builder.h:93
    #10 0x7f91e904a25d in simdjson::haswell::dom_parser_implementation::stage2_next(simdjson::dom::document&) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../src/haswell/dom_parser_implementation.cpp:152
    #11 0x57e729 in simdjson::dom::document_stream::next() /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../include/simdjson/dom/document_stream-inl.h:202:35
    #12 0x521aaf in simdjson::dom::document_stream::iterator::operator++() /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../include/simdjson/dom/document_stream-inl.h:147:10
    #13 0x521aaf in document_stream_tests::issue1310() /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../tests/document_stream_tests.cpp:154
    #14 0x5715d4 in document_stream_tests::run() /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../tests/document_stream_tests.cpp:502:12
    #15 0x572ca5 in main /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../tests/document_stream_tests.cpp:559:7
    #16 0x7f91e863109a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #17 0x427659 in _start (/home/paul/code/delaktig/simdjson/build-sanitizers-O0/tests/document_stream_tests+0x427659)

0x60700000006f is located 14 bytes to the right of 65-byte region [0x607000000020,0x607000000061)
allocated by thread T0 here:
    #0 0x5029b2 in operator new[](unsigned long, std::nothrow_t const&) (/home/paul/code/delaktig/simdjson/build-sanitizers-O0/tests/document_stream_tests+0x5029b2)
    #1 0x574569 in simdjson::internal::allocate_padded_buffer(unsigned long) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../include/simdjson/padded_string-inl.h:34:25
    #2 0x5106d3 in simdjson::padded_string::padded_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../include/simdjson/padded_string-inl.h:60:42
    #3 0x51d23d in document_stream_tests::issue1310() /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../tests/document_stream_tests.cpp:146:43
    #4 0x5715d4 in document_stream_tests::run() /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../tests/document_stream_tests.cpp:502:12
    #5 0x572ca5 in main /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../tests/document_stream_tests.cpp:559:7
    #6 0x7f91e863109a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/paul/code/delaktig/simdjson/build-sanitizers-O0/../include/simdjson/haswell/simd.h:78:14 in simdjson::haswell::(anonymous namespace)::simd::base8_numeric<unsigned char>::load(unsigned char const*)
Shadow bytes around the buggy address:
  0x0c0e7fff7fb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c0e7fff7fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c0e7fff7fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c0e7fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c0e7fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c0e7fff8000: fa fa fa fa 00 00 00 00 00 00 00 00 01[fa]fa fa
  0x0c0e7fff8010: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0e7fff8020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0e7fff8030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0e7fff8040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0e7fff8050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==9949==ABORTING

```

**Comment by lemire** [comment]
@pauldreik I think your tests have revealed an underlying issue that was introduced during a simplification of this code.

So there is a real design bug in there.

**Comment by lemire** [comment]
I have high hopes that PR https://github.com/simdjson/simdjson/pull/1321 will fix this, or, at least, fix part of it.

**Comment by lemire** [comment]
(This code is particularly tricky to get right. Notice how I am very carefully being surgical.)

**Comment by lemire** [comment]
I am going to close for now since I cannot see a clear target to identify a problem at this time.
