### ISSUE TITLE
Design not intuitive. Simple implementation results in SIGSEGV

### ISSUE THREAD

**Issue by satyapravin** [simdjson/simdjson#1783]
I tried to implement a wrapper over simdjson and following code results in SIGSEGV.

Linux LAPTOP-RFEEOME0 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```        
class Config {
 public:
     Config(const std::string& r) { doc  = parser.parse(r); }

private:
     simdjson::dom::parser parser;
     simdjson::simdjson_result<simdjson::dom::element> doc;
};

std::string json; // some json string
Config cfg(json);        
```

The gdb output is as follows:

```
Program received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0x32d) at malloc.c:3102
3102    malloc.c: No such file or directory.
(gdb) where
#0  __GI___libc_free (mem=0x32d) at malloc.c:3102
#1  0x00005555555632e1 in std::enable_if<std::is_convertible<char (*) [], char (*) []>::value, void>::type std::default_delete<char []>::operator()<char>(char*) const ()
#2  0x0000555555562817 in std::unique_ptr<char [], std::default_delete<char []> >::~unique_ptr() ()
#3  0x0000555555561380 in simdjson::dom::parser::~parser() ()
#4  0x00005555555622c4 in OptionArber::Base::Config::~Config() ()
```

The CMake

```
$ cat CMakeLists.txt
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
```

**Comment by lemire** [comment]
I cannot reproduce. Please re-open a new issue with enough details so that we can reproduce the error.

I took the following program:
```C++
#include "simdjson.cpp"
#include "simdjson.h"

#include <string>
#include <iostream>
class Config {
 public:
     Config(const std::string& r) { doc  = parser.parse(r); }

private:
     simdjson::dom::parser parser;
     simdjson::simdjson_result<simdjson::dom::element> doc;
};


int main() {
    std::string json =  "[1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,10000000,100000]";
    Config cfg(json);
}
```

I compiled it as such...

```
c++ issue.cpp -std=c++11
```

I ran it through valgrind:

```
$ valgrind ./a.out
==2154== Memcheck, a memory error detector
==2154== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==2154== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==2154== Command: ./a.out
==2154==
==2154==
==2154== HEAP SUMMARY:
==2154==     in use at exit: 0 bytes in 0 blocks
==2154==   total heap usage: 14 allocs, 14 frees, 83,246 bytes allocated
==2154==
==2154== All heap blocks were freed -- no leaks are possible
==2154==
==2154== For counts of detected and suppressed errors, rerun with: -v
==2154== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

I tried gdb...

```
$ gdb ./a.out
GNU gdb (Ubuntu 8.2-0ubuntu1~16.04.1) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./a.out...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/dlemire/CVS/github/simdjson/singleheader/a.out
[Inferior 1 (process 2163) exited normally]
```

**Comment by lemire** [comment]
Bugs are always possible but please note that the library is very well tested. If you think there is an issue, please consider providing a unit test that allows us to reproduce the problem.
