### ISSUE TITLE
unsafe precondition(s) violated: ptr::write requires that the pointer argument is aligned and non-null

### ISSUE THREAD

**Issue by richarddd** [simdjson/simdjson#2102]
**Describe the bug**
There seems to be some alignment issues in neon implementation.

My program panics when trying to parse the following json:

```json
{"type":"Buffer","data":[10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10]}
```
```shell
thread 'json::tests::json_parser' panicked at /Users/ridaviso/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panicking.rs:155:5:
unsafe precondition(s) violated: ptr::write requires that the pointer argument is aligned and non-null
stack backtrace:
   0: rust_begin_unwind
             at /Users/ridaviso/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_nounwind_fmt::runtime
             at /Users/ridaviso/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panicking.rs:110:18
   2: core::panicking::panic_nounwind_fmt
             at /Users/ridaviso/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panicking.rs:122:9
   3: core::panicking::panic_nounwind
             at /Users/ridaviso/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panicking.rs:155:5
   4: core::ptr::write::runtime
             at /Users/ridaviso/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/intrinsics.rs:2545:21
   5: core::ptr::write
             at /Users/ridaviso/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:1411:9
   6: <simd_json::impls::neon::stage1::SimdInput as simd_json::Stage1Parse>::flatten_bits
             at /Users/ridaviso/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.13.4/src/impls/neon/stage1.rs:205:13
   7: simd_json::Deserializer::_find_structural_bits
             at /Users/ridaviso/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.13.4/src/lib.rs:1069:9
   8: simd_json::Deserializer::find_structural_bits
             at /Users/ridaviso/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.13.4/src/lib.rs:797:9
   9: simd_json::Deserializer::fill_tape
             at /Users/ridaviso/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.13.4/src/lib.rs:889:13
  10: simd_json::Deserializer::from_slice_with_buffers
             at /Users/ridaviso/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.13.4/src/lib.rs:912:9
  11: simd_json::Deserializer::from_slice
```

**To Reproduce**
Its a bit hard to reproduce since this is alignment issue so depends on where a the json string is stored in memory. But his is what i'm doing:

```rust
pub fn json_parse(mut json: Vec<u8>){
  simd_json::to_tape(&mut json).unwrap();
}
```

**simjson release**
v3.6.3

**Comment by richarddd** [comment]
Whops, wrong repo!
