### ISSUE TITLE
Segmentation fault when reusing parser (load) inside loop

### ISSUE THREAD

**Issue by knapply** [simdjson/simdjson#938]
I have not seen examples showing this specifically, but everything strongly suggests that the parser should be reused to the maximum extent possible (and it works w/ previous versions).

**Describe the bug**
`simdjson::parser::load()` segfaults when the parser is reused in a loop.

Encountered with most recent amalgamation (Fri 12 Jun 2020 13:09:36 EDT) during experiments for https://github.com/eddelbuettel/rcppsimdjson and reproduced without any R involved.

I have not been able to reproduce w/ previous versions (Wed May 20 10:23:07 EDT 2020).
I've also tried upping the max capacity w/o success.

**To Reproduce**

A temporary repo w/ everything is here: https://github.com/knapply/simdjson-playground.

```cpp
#include "simdjson.h"

int main() {
  std::vector<std::string> json_strings{"[true,false]", "[1,2,3,null]",
                                        R"({"yay":"json!"})"};
  simdjson::dom::parser parser1;
  for (simdjson::padded_string str : json_strings) {  // no problem ============
    auto [element, error] = parser1.parse(str);

    std::cout << element << std::endl;
  }
  //
  std::vector<std::string> file_paths{
      "adversarial.json",      "flatadversarial.json", "demo.json",
      "twitter_timeline.json", "repeat.json",          "smalldemo.json",
      "truenull.json"};
  //
  std::cout << "\n\nparser inside of loop =======================" << std::endl;
  for (auto path : file_paths) {  // no problem ================================
    simdjson::dom::parser parser2;
    std::cout << "file: " << path << std::endl;
    auto [element, error] = parser2.load(path);
  }
  //
  std::cout << "\n\nparser outside of loop ======================" << std::endl;
  simdjson::dom::parser parser3;
  for (auto path : file_paths) {  // segmentation fault ========================
    std::cout << "file: " << path << std::endl;

    auto [element, error] = parser3.load(path);

    std::cout << "\t- error? " << error << std::endl;
  }

  return 0;
}
```

All of the following have the same result (or similar w/ different file combinations).

```sh
g++-10 -std=c++17 -o test test.cpp simdjson.cpp && ./test
g++-9 -std=c++17 -o test test.cpp simdjson.cpp && ./test
g++-8 -std=c++17 -o test test.cpp simdjson.cpp && ./test
g++-7 -std=c++17 -o test test.cpp simdjson.cpp && ./test
clang++-10 -std=c++17 -o test test.cpp simdjson.cpp && ./test
clang++-6.0 -std=c++17 -o test test.cpp simdjson.cpp && ./test
...
[true,false]
[1,2,3,null]
{"yay":"json!"}


parser inside of loop =======================
file: adversarial.json
file: flatadversarial.json
file: demo.json
file: twitter_timeline.json
file: repeat.json
file: smalldemo.json
file: truenull.json


parser outside of loop ======================
file: adversarial.json
	- error? No error
file: flatadversarial.json
	- error? No error
file: demo.json
	- error? No error
file: twitter_timeline.json
Segmentation fault (core dumped)
```

**Configuration (please complete the following information if relevant):**
 - OS: Ubuntu 18.04 LTS
 - Compiler
    + GCC
    + Clang
 - Version
    + GCC:7,  8, 9, 10
    + Clang: 6.0, 10

**Indicate whether you are willing or able to provide a bug fix as a pull request**
Willing, but I'm not confident I'm able.

**Comment by lemire** [comment]
Verified https://github.com/simdjson/simdjson/pull/940

**Comment by lemire** [comment]
@knapply  Thank you for the detailed report and for providing a reproducible case. 

The bug is real. This is not acceptable and we need to fix the issue before the next issue.

**Comment by lemire** [comment]
The problem is apparently a lack of capacity issue... It may have been introduced in the recent reengineering work...

```
=================================================================
==90312==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x610000001c08 at pc 0x00010da36f8a bp 0x7ffee23158d0 sp 0x7ffee23158c8
WRITE of size 32 at 0x610000001c08 thread T0
    #0 0x10da36f89 in simdjson::error_code simdjson::haswell::stage2::(anonymous namespace)::parse_structurals<false>(simdjson::haswell::dom_parser_implementation&, simdjson::dom::document&) (libsimdjson.dylib:x86_64+0x4df89)
    #1 0x10da27fea in simdjson::haswell::dom_parser_implementation::stage2(simdjson::dom::document&) (libsimdjson.dylib:x86_64+0x3efea)
    #2 0x10d95e86e in simdjson::dom::parser::parse(unsigned char const*, unsigned long, bool) & (basictests:x86_64+0x10007586e)
    #3 0x10d8ef8e2 in simdjson::dom::parser::load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) & (basictests:x86_64+0x1000068e2)
    #4 0x10d8ee67f in document_tests::issue938() (basictests:x86_64+0x10000567f)
    #5 0x10d95db08 in main (basictests:x86_64+0x100074b08)
    #6 0x7fff6f4e6cc8 in start (libdyld.dylib:x86_64+0x1acc8)

0x610000001c08 is located 8 bytes to the right of 192-byte region [0x610000001b40,0x610000001c00)
allocated by thread T0 here:
    #0 0x10db072fd in wrap__ZnamRKSt9nothrow_t (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x522fd)
    #1 0x10d95f7b3 in simdjson::dom::document::allocate(unsigned long) (basictests:x86_64+0x1000767b3)
    #2 0x10d95e69d in simdjson::dom::parser::parse(unsigned char const*, unsigned long, bool) & (basictests:x86_64+0x10007569d)
    #3 0x10d8ef8e2 in simdjson::dom::parser::load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) & (basictests:x86_64+0x1000068e2)
    #4 0x10d8ee67f in document_tests::issue938() (basictests:x86_64+0x10000567f)
    #5 0x10d95db08 in main (basictests:x86_64+0x100074b08)
    #6 0x7fff6f4e6cc8 in start (libdyld.dylib:x86_64+0x1acc8)

SUMMARY: AddressSanitizer: heap-buffer-overflow (libsimdjson.dylib:x86_64+0x4df89) in simdjson::error_code simdjson::haswell::stage2::(anonymous namespace)::parse_structurals<false>(simdjson::haswell::dom_parser_implementation&, simdjson::dom::document&)
Shadow bytes around the buggy address:
  0x1c2000000330: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x1c2000000340: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x1c2000000350: fd fd fd fd fd fd fa fa fa fa fa fa fa fa fa fa
  0x1c2000000360: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x1c2000000370: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x1c2000000380: fa[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c2000000390: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c20000003a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c20000003b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c20000003c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c20000003d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==90312==ABORTING
Abort trap: 6
```

**Comment by lemire** [comment]
I think that the fix is trivial but I will wait for @jkeiser  to verify.

In your loop, the parser has to reallocate memory. It does so. But then it fails to reallocate the memory to hold the document... because <reason>... I removed the branch that would opt out of reallocating the document's buffer and it seems to fix the issue.

I can't figure out why we have this branch in there. This might just be a copy-paste bug.

I am annoyed that our tests would not catch this problem automatically. It is annoying.

**Comment by lemire** [comment]
A fix is in a PR.
